#!/bin/bash

# @link https://gist.github.com/mattscilipoti/8424018
#
# Called by "git push" after it has checked the remote status,
# but before anything has been pushed.
#
# If this script exits with a non-zero status nothing will be pushed.
#
# Steps to install, from the root directory of your repo...
# 1. Copy the file into your repo at `.git/hooks/pre-push`
# 2. Set executable permissions, run `chmod +x .git/hooks/pre-push`
# 3. Or, use `rake hooks:pre_push` to install
#
# Try a push to master or main, you should get a message `*** [Policy] Never push code directly to...`
#
# The commands below will not be allowed...
# `git push origin master`
# `git push origin main`
# `git push --force origin master`
# `git push --force origin main`
# `git push --delete origin master`
# `git push --delete origin main`


protected_branch_1='master'
protected_branch_2='main'

policy="\n\n[Policy] Never push code directly to the "$protected_branch_1" and "$protected_branch_2" branch! (Prevented with pre-push hook.)\n\n"

current_branch=$(git branch --show-current)

push_command=$(ps -ocommand= -p $PPID)

is_destructive='force|delete|\-f'

will_remove_protected_branch_1=':'$protected_branch_1
will_remove_protected_branch_2=':'$protected_branch_2

do_exit(){
  echo -e $policy
  exit 1
}

# Prevent ALL pushes to protected_branch
if [[ $push_command =~ $protected_branch_1 ]] || [ $current_branch = $protected_branch_1 ] || [[ $push_command =~ $protected_branch_2 ]] || [ $current_branch = $protected_branch_2 ]; then
  do_exit
fi

unset do_exit

exit 0