#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


#branch=`git symbolic-ref HEAD`
#if [ "$branch" = "refs/heads/main" ]; then
#    echo "Direct commits to the branch main are not allowed"
#    exit 1
#fi
#
#if [ "$branch" = "refs/heads/master" ]; then
#    echo "Direct commits to the branch main are not allowed"
#    exit 1
#fi